# Dependencies
markdown:         redcarpet
pygments:         true

# Permalinks
permalink:        pretty

# Setup
title:            Dev Blog
tagline:          'I can haz web development career?'
description:      'My web development journey build in Jekyll with Poole. Theme by <a href="https://twitter.com/mdo" target="_blank">@mdo</a>.'
url:              https://juddnutting.github.io

author:
  name:           'Judd Nutting'
  url:            https://twitter.com/juddnutting

paginate:         5

# Custom vars
version:          2.0.0

github_username:  'juddnutting'
twitter_username: 'juddnutting'

github:           
  repo:           https://github.com/Juddnutting/juddnutting.github.com
